image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y node
    - gem install dpl

stages:
    - production

production:
    type: deploy
    stage: production
    image: node:lts-alpine
    script:
        - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    only:
        - main